import ConfigurablePanel from "/apogeeui/configurablepanel/ConfigurablePanel.js";
import CheckboxElement from "/apogeeui/configurablepanel/elements/CheckboxElement.js";
import CheckboxGroupElement from "/apogeeui/configurablepanel/elements/CheckboxGroupElement.js";
import CustomElement from "/apogeeui/configurablepanel/elements/CustomElement.js";
import DropdownElement from "/apogeeui/configurablepanel/elements/DropdownElement.js";
import HeadingElement from "/apogeeui/configurablepanel/elements/HeadingElement.js";
import HTMLDisplayElement from "/apogeeui/configurablepanel/elements/HTMLDisplayElement.js";
import InvisibleElement from "/apogeeui/configurablepanel/elements/InvisibleElement.js";
import PanelElement from "/apogeeui/configurablepanel/elements/PanelElement.js";
import RadioGroupElement from "/apogeeui/configurablepanel/elements/RadioGroupElement.js";
import SpacerElement from "/apogeeui/configurablepanel/elements/SpacerElement.js";
import SubmitElement from "/apogeeui/configurablepanel/elements/SubmitElement.js";
import TextareaElement from "/apogeeui/configurablepanel/elements/TextareaElement.js";
import TextFieldElement from "/apogeeui/configurablepanel/elements/TextFieldElement.js";

ConfigurablePanel.addConfigurableElement(CheckboxElement);
ConfigurablePanel.addConfigurableElement(CheckboxGroupElement);
ConfigurablePanel.addConfigurableElement(CustomElement);
ConfigurablePanel.addConfigurableElement(DropdownElement);
ConfigurablePanel.addConfigurableElement(HeadingElement);
ConfigurablePanel.addConfigurableElement(HTMLDisplayElement);
ConfigurablePanel.addConfigurableElement(InvisibleElement);
ConfigurablePanel.addConfigurableElement(PanelElement);
ConfigurablePanel.addConfigurableElement(RadioGroupElement);
ConfigurablePanel.addConfigurableElement(SpacerElement);
ConfigurablePanel.addConfigurableElement(SubmitElement);
ConfigurablePanel.addConfigurableElement(TextareaElement);
ConfigurablePanel.addConfigurableElement(TextFieldElement);